on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 18 * * 6'

name: Pull Content
permissions:
  contents: write
jobs:
  build:
  env:
      GITHUB_PAT: ${{ secrets.BUILD_KEY }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.TARGET_REPO }}
          ssh-key: ${{ secrets.PULL_KEY }}
          ref: main
          path: main
          fetch-depth: 0
          run: |
            git pull
            git config user.name BikramHalder
            git config user.email ${{ secrets.USER_EMAIL }}
            git add .
            git commit -m "Pull content"
            git push
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: main

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-5-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-5-

      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps()
        shell: Rscript {0}

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Build book
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Deploy to github-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _book # The folder the action should deploy.

        